# DEV ENVIRONMENT
services:
  api:
    container_name: ags_dev_worker
    restart: always
    build:
      context: .
      dockerfile: ./docker/development/api/Dockerfile
    volumes:
      - ./:/app
      - ./projects:/app/projects
      - ./gama/gama-platform:/opt/gama-platform
    ports:
      - "8080:8080"
    networks:
      - ags_worker_network

networks:
  ags_worker_network:
    driver: bridge
