services:
  api:
    container_name: ags_local_worker
    build:
      context: .
      dockerfile: ./docker/local/api/Dockerfile
    volumes:
      - ./:/app
      - ./projects:/app/projects
      - ./gama/gama-platform:/opt/gama-platform
    ports:
      - "9998:9998"
    networks:
      - ags_worker_network

networks:
  ags_worker_network:
    driver: bridge
