# THIS FILE IS USED FOR DEVELOPMENT ENVIRONMENT - RUN WITH DOCKER
server:
  port: 8080

logging:
  level:
    root: INFO
    redis:
      clients:
        jedis: DEBUG
  file:
    path: storage/logs

# Config database
spring:
  datasource:
    url: jdbc:mysql://172.30.11.8:3306/ags?rewriteBatchedStatements=true
    username: agsuser
    password: mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
      format_sql: true
  data:
    redis:
      host: 172.30.11.8
      port: 6379
      password: redis123456
      database: 0

aws:
  access-key:
  secret-key:
  region:
  s3:
    bucket-name:

jwt:
  secret: dt}kkS%py8,Xh30!GLWr@FE@7CC,x@#d-{vni9fvjumkgS.6ex056?7RJgH?a=}K
  ttl: 7776000000
  refresh_ttl: 2419200000

gama:
  path:
    shell: /opt/gama-platform/headless/gama-headless.sh
    output: /app/storage/outputs
    xml: /app/storage/xmls
    project: /app/projects
  config:
    frame-rate: 45

cluster:
  config:
    path: src/main/resources/cluster-config.yml
