# THIS FILE IS USED FOR LOCAL ENVIRONMENT - RUN WITHOUT DOCKER
server:
  port: 9998

logging:
  level:
    root: INFO
    redis:
      clients:
        jedis: DEBUG
  file:
    path: storage/logs

# Config database
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/ags?rewriteBatchedStatements=true
    username: agsuser
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: false
      format_sql: true
  data:
    redis:
      host: localhost
      port: 16379
      password: 123
      database: 0

aws:
  access-key:
  secret-key:
  region:
  s3:
    bucket-name:

jwt:
  secret: dt}kkS%py8,Xh30!GLWr@FE@7CC,x@#d-{vni9fvjumkgS.6ex056?7RJgH?a=}K
  ttl: 604800000
  refresh_ttl: 2419200000

gama:
  path:
    shell: gama/gama-platform/headless/gama-headless.sh
    output: /Users/trungdt/Workspaces/uet/agent_simulation/gama/outputs
    xml: /Users/trungdt/Workspaces/uet/agent_simulation/gama/xmls
    project: /Users/trungdt/Workspaces/uet/agent_simulation/gama/projects
  config:
    frame-rate: 45

cluster:
  config:
    path: src/main/resources/cluster-config.yml
